#ifndef RINGTOSS_MODEL_COEFFICIENTS_H
#define RINGTOSS_MODEL_COEFFICIENTS_H

// Placeholder model for compile-time testing.
// Replace this file with the header generated by tools/ringtoss_train.py.

#define RINGTOSS_MODEL_READY 0

const uint8_t RINGTOSS_FEATURE_COUNT = 20;
const uint8_t RINGTOSS_CLASS_COUNT = 9;
const uint8_t RINGTOSS_VECTOR_OUTPUT_COUNT = 4;

const float RINGTOSS_FEATURE_MEAN[RINGTOSS_FEATURE_COUNT] = {0.0f};

const float RINGTOSS_FEATURE_SCALE[RINGTOSS_FEATURE_COUNT] = {
  1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f,
  1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f, 1.0f
};

const float RINGTOSS_CLASS_INTERCEPT[RINGTOSS_CLASS_COUNT] = {0.0f};
const float RINGTOSS_CLASS_COEF[RINGTOSS_CLASS_COUNT][RINGTOSS_FEATURE_COUNT] = {{0.0f}};

const float RINGTOSS_VECTOR_INTERCEPT[RINGTOSS_VECTOR_OUTPUT_COUNT] = {
  0.0f, 0.0f, 1.0f, 1.0f
};
const float RINGTOSS_VECTOR_COEF[RINGTOSS_VECTOR_OUTPUT_COUNT][RINGTOSS_FEATURE_COUNT] = {{0.0f}};

#endif
